/**
 * LORIS API
 * This document specifies the LORIS REST API.
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LorisApi) {
      root.LorisApi = {};
    }
    root.LorisApi.Candidate = factory(root.LorisApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Candidate model module.
   * @module model/Candidate
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>Candidate</code>.
   * @alias module:model/Candidate
   * @class
   * @param dob {Date} 
   * @param sex {module:model/Candidate.SexEnum} 
   */
  var exports = function(dob, sex) {
    var _this = this;



    _this['dob'] = dob;

    _this['sex'] = sex;
  };

  /**
   * Constructs a <code>Candidate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Candidate} obj Optional instance to populate.
   * @return {module:model/Candidate} The populated <code>Candidate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('project')) {
        obj['project'] = ApiClient.convertToType(data['project'], 'String');
      }
      if (data.hasOwnProperty('pscid')) {
        obj['pscid'] = ApiClient.convertToType(data['pscid'], 'String');
      }
      if (data.hasOwnProperty('dob')) {
        obj['dob'] = ApiClient.convertToType(data['dob'], 'Date');
      }
      if (data.hasOwnProperty('edc')) {
        obj['edc'] = ApiClient.convertToType(data['edc'], 'Date');
      }
      if (data.hasOwnProperty('sex')) {
        obj['sex'] = ApiClient.convertToType(data['sex'], 'String');
      }
    }
    return obj;
  }

  /**
   * The name of the project to add this candidate to.
   * @member {String} project
   * @default 'LORIS'
   */
  exports.prototype['project'] = 'LORIS';
  /**
   * Required if the pscid setting of the project is set to `prompt`
   * @member {String} pscid
   */
  exports.prototype['pscid'] = undefined;
  /**
   * @member {Date} dob
   */
  exports.prototype['dob'] = undefined;
  /**
   * Expected date of confinement, required only if the project use EDC.
   * @member {Date} edc
   */
  exports.prototype['edc'] = undefined;
  /**
   * @member {module:model/Candidate.SexEnum} sex
   */
  exports.prototype['sex'] = undefined;


  /**
   * Allowed values for the <code>sex</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SexEnum = {
    /**
     * value: "Male"
     * @const
     */
    "Male": "Male",
    /**
     * value: "Female"
     * @const
     */
    "Female": "Female"  };


  return exports;
}));


