/**
 * LORIS API
 * This document specifies the LORIS REST API.
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LorisApi) {
      root.LorisApi = {};
    }
    root.LorisApi.ImageFileDescription = factory(root.LorisApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ImageFileDescription model module.
   * @module model/ImageFileDescription
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>ImageFileDescription</code>.
   * @alias module:model/ImageFileDescription
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ImageFileDescription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageFileDescription} obj Optional instance to populate.
   * @return {module:model/ImageFileDescription} The populated <code>ImageFileDescription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('OutputType')) {
        obj['OutputType'] = ApiClient.convertToType(data['OutputType'], 'String');
      }
      if (data.hasOwnProperty('Filename')) {
        obj['Filename'] = ApiClient.convertToType(data['Filename'], 'String');
      }
      if (data.hasOwnProperty('AcquisitionType')) {
        obj['AcquisitionType'] = ApiClient.convertToType(data['AcquisitionType'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} OutputType
   */
  exports.prototype['OutputType'] = undefined;
  /**
   * @member {String} Filename
   */
  exports.prototype['Filename'] = undefined;
  /**
   * @member {String} AcquisitionType
   */
  exports.prototype['AcquisitionType'] = undefined;



  return exports;
}));


