/**
 * LORIS API
 * This document specifies the LORIS REST API.
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LorisApi) {
      root.LorisApi = {};
    }
    root.LorisApi.InstrumentData = factory(root.LorisApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InstrumentData model module.
   * @module model/InstrumentData
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>InstrumentData</code>.
   * That instrument data entry progress and values
   * @alias module:model/InstrumentData
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InstrumentData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InstrumentData} obj Optional instance to populate.
   * @return {module:model/InstrumentData} The populated <code>InstrumentData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('flags')) {
        obj['flags'] = ApiClient.convertToType(data['flags'], Object);
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], Object);
      }
    }
    return obj;
  }

  /**
   * progress status of that instrument
   * @member {Object} flags
   */
  exports.prototype['flags'] = undefined;
  /**
   * A set key:value pairs where the keys are the quetions and values are the answers.
   * @member {Object} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


